openapi: 3.0.0
info:
  title: JetBrains assignement web application server
  description: That server implements points from JetBrains assignement
  version: 0.1.0-SNAPSHOT
paths:
  /:
    get:
      summary: Returns login page
      description: Returns login page or redirect to personal area (/pa) page when user already logged in
      responses:
#        '200':
#          description: A simple HTML page
#          content:
#            text/html:
#              schema:
#                type: string
#        '302':
#          description: Redirect to personal area page
#          headers:
#            Location:
#              description: Location to redirect to
#              schema:
#                type: string
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
  /pa:
    get:
      summary: Return personal area page
      description: Returns personal area page or redirect to login (/) page if user is not logged in
      responses:
#        '200':
#          description: A simple HTML page
#          content:
#            text/html:
#              schema:
#                type: string
#        '302':
#          description: Redirect to personal area page
#          headers:
#            Location:
#              description: Location to redirect to
#              schema:
#                type: string
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
  /user:
    post:
      summary: Create new user
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/User'
      responses:
#        '201':
#          description: Created
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/User'
#        '401':
#          description: User creating allowed only for authorized ADMIN users
#        '403':
#          description: User creating not allowed for current user
#        '409':
#          description: New user conflicted with early created users
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
  /session:
    post:
      summary: Create new session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '400':
          description: Unable to create session for current user (wrong username/password)
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
  /password:
    put:
      summary: Update current user password
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/User'
      responses:
#        '200':
#          description: Password succeffuly updated
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/User'
#        '401':
#          description: Unauthorized
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
  /user/session:
    get:
      summary: Retrieve current user session
      responses:
#        '200':
#          description: Current user session
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/User'
#        '401':
#          description: Unauthorized
#        '403':
#          description: Session retrieving not allowed for current user
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
  /reviewer/metrics:
    get:
      summary: Retrieve metrics
      responses:
#        '200':
#          description: Metrics
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Metrics'
#        '401':
#          description: Unauthorized
#        '403':
#          description: Session retrieving not allowed for current user
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
  /admin/users:
    get:
      summary: Retrieve all known users
      responses:
#        '200':
#          description: Users
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  $ref: '#/components/schemas/User'
#        '401':
#          description: Unauthorized
#        '403':
#          description: Session retrieving not allowed for current user
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [ "USER", "REVIEWER", "ADMIN" ]
    Password:
      type: object
      properties:
        password:
          type: string
    Credentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    Session:
      type: object
      properties:
        username:
          type: string
        role:
          type: string
          enum: [ "USER", "REVIEWER", "ADMIN" ]
        token:
          type: string
    Metrics:
      type: object
      properties:
        activeSessionCount:
          type: integer