openapi: 3.0.0
info:
  title: JetBrains assignement web application server
  description: That server implements points from JetBrains assignement
  version: 0.1.0-SNAPSHOT
paths:
  /users:
    post:
      summary: Create new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: User creating allowed only for authorized ADMIN users
        '403':
          description: User creating not allowed for current user
        '409':
          description: New user conflicted with early created users
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
  /sessions:
    post:
      summary: Create new session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '400':
          description: Unable to create session for current user (wrong username/password)
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
  /users/password:
    put:
      summary: Update current user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Password'
      responses:
        '200':
          description: Password succeffuly updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
        '501':
          description: Method not implemented yet
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [ "USER", "REVIEWER", "ADMIN" ]
    Password:
      type: object
      properties:
        password:
          type: string
    Credentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    Session:
      type: object
      properties:
        username:
          type: string
        role:
          type: string
          enum: [ "USER", "REVIEWER", "ADMIN" ]
        token:
          type: string